2025-03-17 22:24:58.379 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-17 22:24:58.583 [info] [Info  - 10:24:58 PM] (12408) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-17 22:24:58.585 [info] [Info  - 10:24:58 PM] (12408) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-17 22:24:58.590 [info] [Info  - 10:24:58 PM] (12408) Starting service instance "getya proyecto"
2025-03-17 22:24:58.630 [info] [Info  - 10:24:58 PM] (12408) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-17 22:24:58.631 [info] [Info  - 10:24:58 PM] (12408) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-17 22:24:58.631 [info] [Info  - 10:24:58 PM] (12408) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-17 22:24:58.631 [info] [Info  - 10:24:58 PM] (12408) Auto-excluding **/node_modules
2025-03-17 22:24:58.631 [info] [Info  - 10:24:58 PM] (12408) Auto-excluding **/__pycache__
2025-03-17 22:24:58.632 [info] [Info  - 10:24:58 PM] (12408) Auto-excluding **/.*
2025-03-17 22:24:58.941 [info] [Info  - 10:24:58 PM] (12408) Assuming Python version 3.13.2.final.0
2025-03-17 22:24:59.139 [info] [Info  - 10:24:59 PM] (12408) No source files found.
2025-03-17 22:24:59.544 [info] [Info  - 10:24:59 PM] (12408) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-17 22:24:59.546 [info] [Info  - 10:24:59 PM] (12408) Background analysis(1) started
2025-03-17 22:24:59.807 [info] [Info  - 10:24:59 PM] (12408) Indexer background runner(2) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-17 22:24:59.807 [info] [Info  - 10:24:59 PM] (12408) Indexing(2) started
2025-03-17 22:25:00.792 [info] [Info  - 10:25:00 PM] (12408) scanned(2) 11 files over 1 exec env
2025-03-17 22:25:00.941 [info] [Info  - 10:25:00 PM] (12408) indexed(2) 11 files over 1 exec env
2025-03-17 22:25:00.953 [info] [Info  - 10:25:00 PM] (12408) Indexing finished(2).
2025-03-17 22:25:02.358 [info] [Info  - 10:25:02 PM] (12408) Starting service instance "<default>"
2025-03-17 22:25:02.377 [info] [Info  - 10:25:02 PM] (12408) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-17 22:25:02.377 [info] [Info  - 10:25:02 PM] (12408) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-17 22:25:02.377 [info] [Info  - 10:25:02 PM] (12408) No include entries specified; assuming \<default workspace root>
2025-03-17 22:25:02.377 [info] [Info  - 10:25:02 PM] (12408) Auto-excluding **/node_modules
2025-03-17 22:25:02.378 [info] [Info  - 10:25:02 PM] (12408) Auto-excluding **/__pycache__
2025-03-17 22:25:02.378 [info] [Info  - 10:25:02 PM] (12408) Auto-excluding **/.*
2025-03-17 22:25:02.437 [info] [Info  - 10:25:02 PM] (12408) Assuming Python version 3.13.2.final.0
2025-03-17 22:25:02.572 [info] [Error - 10:25:02 PM] (12408) File or directory "\<default workspace root>" does not exist.
2025-03-17 22:25:02.572 [info] [Info  - 10:25:02 PM] (12408) No source files found.
2025-03-17 22:25:02.992 [info] [Info  - 10:25:02 PM] (12408) Background analysis(3) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-17 22:25:02.995 [info] [Info  - 10:25:02 PM] (12408) Background analysis(3) started
2025-03-18 00:36:03.829 [info] [Info  - 12:36:03 AM] (12408) Found 1 source file
2025-03-18 00:37:45.445 [info] [Info  - 12:37:45 AM] Server process exited successfully
2025-03-18 00:37:45.950 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-18 00:37:46.451 [info] [Info  - 12:37:46 AM] (11884) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-18 00:37:46.453 [info] [Info  - 12:37:46 AM] (11884) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-18 00:37:46.458 [info] [Info  - 12:37:46 AM] (11884) Starting service instance "getya proyecto"
2025-03-18 00:37:46.487 [info] [Info  - 12:37:46 AM] (11884) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-18 00:37:46.487 [info] [Info  - 12:37:46 AM] (11884) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-18 00:37:46.487 [info] [Info  - 12:37:46 AM] (11884) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-18 00:37:46.488 [info] [Info  - 12:37:46 AM] (11884) Auto-excluding **/node_modules
2025-03-18 00:37:46.488 [info] [Info  - 12:37:46 AM] (11884) Auto-excluding **/__pycache__
2025-03-18 00:37:46.488 [info] [Info  - 12:37:46 AM] (11884) Auto-excluding **/.*
2025-03-18 00:37:46.547 [info] [Info  - 12:37:46 AM] (11884) Assuming Python version 3.13.2.final.0
2025-03-18 00:37:46.724 [info] [Info  - 12:37:46 AM] (11884) Found 1 source file
2025-03-18 00:37:47.151 [info] [Info  - 12:37:47 AM] (11884) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-18 00:37:47.153 [info] [Info  - 12:37:47 AM] (11884) Background analysis(1) started
2025-03-18 00:37:47.327 [info] [Info  - 12:37:47 AM] (11884) Indexer background runner(2) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-18 00:37:47.327 [info] [Info  - 12:37:47 AM] (11884) Indexing(2) started
2025-03-18 00:37:48.168 [info] [Info  - 12:37:48 AM] (11884) scanned(2) 11 files over 1 exec env
2025-03-18 00:37:48.307 [info] [Info  - 12:37:48 AM] (11884) indexed(2) 11 files over 1 exec env
2025-03-18 00:37:48.317 [info] [Info  - 12:37:48 AM] (11884) Indexing finished(2).
2025-03-18 00:38:56.016 [info] [Info  - 12:38:56 AM] Server process exited successfully
2025-03-18 00:38:56.557 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-18 00:38:57.066 [info] [Info  - 12:38:57 AM] (14824) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-18 00:38:57.068 [info] [Info  - 12:38:57 AM] (14824) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-18 00:38:57.073 [info] [Info  - 12:38:57 AM] (14824) Starting service instance "getya proyecto"
2025-03-18 00:38:57.100 [info] [Info  - 12:38:57 AM] (14824) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-18 00:38:57.100 [info] [Info  - 12:38:57 AM] (14824) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-18 00:38:57.100 [info] [Info  - 12:38:57 AM] (14824) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-18 00:38:57.101 [info] [Info  - 12:38:57 AM] (14824) Auto-excluding **/node_modules
2025-03-18 00:38:57.101 [info] [Info  - 12:38:57 AM] (14824) Auto-excluding **/__pycache__
2025-03-18 00:38:57.101 [info] [Info  - 12:38:57 AM] (14824) Auto-excluding **/.*
2025-03-18 00:38:57.157 [info] [Info  - 12:38:57 AM] (14824) Assuming Python version 3.13.2.final.0
2025-03-18 00:38:57.314 [info] [Info  - 12:38:57 AM] (14824) Found 1 source file
2025-03-18 00:38:57.705 [info] [Info  - 12:38:57 AM] (14824) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-18 00:38:57.707 [info] [Info  - 12:38:57 AM] (14824) Background analysis(1) started
2025-03-18 00:38:57.918 [info] [Info  - 12:38:57 AM] (14824) Indexer background runner(2) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-18 00:38:57.918 [info] [Info  - 12:38:57 AM] (14824) Indexing(2) started
2025-03-18 00:38:58.674 [info] [Info  - 12:38:58 AM] (14824) scanned(2) 11 files over 1 exec env
2025-03-18 00:38:58.821 [info] [Info  - 12:38:58 AM] (14824) indexed(2) 11 files over 1 exec env
2025-03-18 00:38:58.831 [info] [Info  - 12:38:58 AM] (14824) Indexing finished(2).
2025-03-18 00:39:11.592 [info] [Info  - 12:39:11 AM] (14824) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-18 00:39:11.593 [info] [Info  - 12:39:11 AM] (14824) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-18 00:39:11.593 [info] [Info  - 12:39:11 AM] (14824) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-18 00:39:11.593 [info] [Info  - 12:39:11 AM] (14824) Auto-excluding **/node_modules
2025-03-18 00:39:11.593 [info] [Info  - 12:39:11 AM] (14824) Auto-excluding **/__pycache__
2025-03-18 00:39:11.594 [info] [Info  - 12:39:11 AM] (14824) Auto-excluding **/.*
2025-03-18 00:39:11.683 [info] [Info  - 12:39:11 AM] (14824) Assuming Python version 3.13.2.final.0
2025-03-18 00:39:11.857 [info] [Info  - 12:39:11 AM] (14824) Found 1 source file
2025-03-18 00:39:13.453 [info] [Info  - 12:39:13 AM] Server process exited successfully
2025-03-18 00:39:13.994 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-18 00:39:14.635 [info] [Info  - 12:39:14 AM] (9404) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-18 00:39:14.637 [info] [Info  - 12:39:14 AM] (9404) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-18 00:39:14.643 [info] [Info  - 12:39:14 AM] (9404) Starting service instance "getya proyecto"
2025-03-18 00:39:14.680 [info] [Info  - 12:39:14 AM] (9404) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-18 00:39:14.680 [info] [Info  - 12:39:14 AM] (9404) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-18 00:39:14.680 [info] [Info  - 12:39:14 AM] (9404) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-18 00:39:14.681 [info] [Info  - 12:39:14 AM] (9404) Auto-excluding **/node_modules
2025-03-18 00:39:14.681 [info] [Info  - 12:39:14 AM] (9404) Auto-excluding **/__pycache__
2025-03-18 00:39:14.681 [info] [Info  - 12:39:14 AM] (9404) Auto-excluding **/.*
2025-03-18 00:39:14.742 [info] [Info  - 12:39:14 AM] (9404) Assuming Python version 3.13.2.final.0
2025-03-18 00:39:14.906 [info] [Info  - 12:39:14 AM] (9404) Found 1 source file
2025-03-18 00:39:15.358 [info] [Info  - 12:39:15 AM] (9404) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-18 00:39:15.360 [info] [Info  - 12:39:15 AM] (9404) Background analysis(1) started
2025-03-18 00:39:15.517 [info] [Info  - 12:39:15 AM] (9404) Indexer background runner(2) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-18 00:39:15.517 [info] [Info  - 12:39:15 AM] (9404) Indexing(2) started
2025-03-18 00:39:16.424 [info] [Info  - 12:39:16 AM] (9404) scanned(2) 11 files over 1 exec env
2025-03-18 00:39:16.576 [info] [Info  - 12:39:16 AM] (9404) indexed(2) 11 files over 1 exec env
2025-03-18 00:39:16.587 [info] [Info  - 12:39:16 AM] (9404) Indexing finished(2).
2025-03-18 00:39:19.683 [info] [Info  - 12:39:19 AM] Server process exited successfully
2025-03-18 00:39:20.282 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-18 00:39:20.969 [info] [Info  - 12:39:20 AM] (9896) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-18 00:39:20.971 [info] [Info  - 12:39:20 AM] (9896) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-18 00:39:20.978 [info] [Info  - 12:39:20 AM] (9896) Starting service instance "getya proyecto"
2025-03-18 00:39:21.029 [info] [Info  - 12:39:21 AM] Server process exited successfully
2025-03-18 00:39:21.533 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-18 00:39:22.144 [info] [Info  - 12:39:22 AM] (9832) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-18 00:39:22.146 [info] [Info  - 12:39:22 AM] (9832) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-18 00:39:22.151 [info] [Info  - 12:39:22 AM] (9832) Starting service instance "getya proyecto"
2025-03-18 00:39:22.190 [info] [Info  - 12:39:22 AM] (9832) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-18 00:39:22.190 [info] [Info  - 12:39:22 AM] (9832) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-18 00:39:22.191 [info] [Info  - 12:39:22 AM] (9832) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-18 00:39:22.192 [info] [Info  - 12:39:22 AM] (9832) Auto-excluding **/node_modules
2025-03-18 00:39:22.192 [info] [Info  - 12:39:22 AM] (9832) Auto-excluding **/__pycache__
2025-03-18 00:39:22.192 [info] [Info  - 12:39:22 AM] (9832) Auto-excluding **/.*
2025-03-18 00:39:22.278 [info] [Info  - 12:39:22 AM] (9832) Assuming Python version 3.13.2.final.0
2025-03-18 00:39:22.456 [info] [Info  - 12:39:22 AM] (9832) Found 1 source file
2025-03-18 00:39:22.870 [info] [Info  - 12:39:22 AM] (9832) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-18 00:39:22.872 [info] [Info  - 12:39:22 AM] (9832) Background analysis(1) started
2025-03-18 00:39:23.078 [info] [Info  - 12:39:23 AM] (9832) Indexer background runner(2) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-18 00:39:23.078 [info] [Info  - 12:39:23 AM] (9832) Indexing(2) started
2025-03-18 00:39:23.954 [info] [Info  - 12:39:23 AM] (9832) scanned(2) 11 files over 1 exec env
2025-03-18 00:39:24.109 [info] [Info  - 12:39:24 AM] (9832) indexed(2) 11 files over 1 exec env
2025-03-18 00:39:24.121 [info] [Info  - 12:39:24 AM] (9832) Indexing finished(2).
2025-03-18 00:39:59.401 [info] [Info  - 12:39:59 AM] Server process exited successfully
2025-03-18 00:39:59.995 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-18 00:40:00.575 [info] [Info  - 12:40:00 AM] (1976) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-18 00:40:00.577 [info] [Info  - 12:40:00 AM] (1976) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-18 00:40:00.582 [info] [Info  - 12:40:00 AM] (1976) Starting service instance "getya proyecto"
2025-03-18 00:40:00.615 [info] [Info  - 12:40:00 AM] (1976) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-18 00:40:00.616 [info] [Info  - 12:40:00 AM] (1976) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-18 00:40:00.617 [info] [Info  - 12:40:00 AM] (1976) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-18 00:40:00.617 [info] [Info  - 12:40:00 AM] (1976) Auto-excluding **/node_modules
2025-03-18 00:40:00.617 [info] [Info  - 12:40:00 AM] (1976) Auto-excluding **/__pycache__
2025-03-18 00:40:00.617 [info] [Info  - 12:40:00 AM] (1976) Auto-excluding **/.*
2025-03-18 00:40:00.681 [info] [Info  - 12:40:00 AM] (1976) Assuming Python version 3.13.2.final.0
2025-03-18 00:40:00.855 [info] [Info  - 12:40:00 AM] (1976) Found 1 source file
2025-03-18 00:40:01.270 [info] [Info  - 12:40:01 AM] (1976) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-18 00:40:01.272 [info] [Info  - 12:40:01 AM] (1976) Background analysis(1) started
2025-03-18 00:40:01.502 [info] [Info  - 12:40:01 AM] (1976) Indexer background runner(2) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-18 00:40:01.502 [info] [Info  - 12:40:01 AM] (1976) Indexing(2) started
2025-03-18 00:40:02.353 [info] [Info  - 12:40:02 AM] (1976) scanned(2) 11 files over 1 exec env
2025-03-18 00:40:02.493 [info] [Info  - 12:40:02 AM] (1976) indexed(2) 11 files over 1 exec env
2025-03-18 00:40:02.504 [info] [Info  - 12:40:02 AM] (1976) Indexing finished(2).
