2025-03-18 00:42:55.157 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-18 00:42:55.244 [info] [Info  - 12:42:55 AM] (18408) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-18 00:42:55.246 [info] [Info  - 12:42:55 AM] (18408) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-18 00:42:55.251 [info] [Info  - 12:42:55 AM] (18408) Starting service instance "getya proyecto"
2025-03-18 00:42:55.296 [info] [Info  - 12:42:55 AM] (18408) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-18 00:42:55.297 [info] [Info  - 12:42:55 AM] (18408) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-18 00:42:55.297 [info] [Info  - 12:42:55 AM] (18408) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-18 00:42:55.298 [info] [Info  - 12:42:55 AM] (18408) Auto-excluding **/node_modules
2025-03-18 00:42:55.298 [info] [Info  - 12:42:55 AM] (18408) Auto-excluding **/__pycache__
2025-03-18 00:42:55.298 [info] [Info  - 12:42:55 AM] (18408) Auto-excluding **/.*
2025-03-18 00:42:55.380 [info] [Info  - 12:42:55 AM] (18408) Assuming Python version 3.13.2.final.0
2025-03-18 00:42:55.539 [info] [Info  - 12:42:55 AM] (18408) Found 1 source file
2025-03-18 00:42:55.978 [info] [Info  - 12:42:55 AM] (18408) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-18 00:42:55.980 [info] [Info  - 12:42:55 AM] (18408) Background analysis(1) started
2025-03-18 00:42:56.277 [info] [Info  - 12:42:56 AM] (18408) Indexer background runner(2) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-18 00:42:56.278 [info] [Info  - 12:42:56 AM] (18408) Indexing(2) started
2025-03-18 00:42:56.984 [info] [Info  - 12:42:56 AM] (18408) scanned(2) 11 files over 1 exec env
2025-03-18 00:42:57.120 [info] [Info  - 12:42:57 AM] (18408) indexed(2) 11 files over 1 exec env
2025-03-18 00:42:57.130 [info] [Info  - 12:42:57 AM] (18408) Indexing finished(2).
2025-03-18 00:42:58.226 [info] [Info  - 12:42:58 AM] (18408) Starting service instance "<default>"
2025-03-18 00:42:58.249 [info] [Info  - 12:42:58 AM] (18408) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-18 00:42:58.250 [info] [Info  - 12:42:58 AM] (18408) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-18 00:42:58.250 [info] [Info  - 12:42:58 AM] (18408) No include entries specified; assuming \<default workspace root>
2025-03-18 00:42:58.250 [info] [Info  - 12:42:58 AM] (18408) Auto-excluding **/node_modules
2025-03-18 00:42:58.250 [info] [Info  - 12:42:58 AM] (18408) Auto-excluding **/__pycache__
2025-03-18 00:42:58.250 [info] [Info  - 12:42:58 AM] (18408) Auto-excluding **/.*
2025-03-18 00:42:58.303 [info] [Info  - 12:42:58 AM] (18408) Assuming Python version 3.13.2.final.0
2025-03-18 00:42:58.424 [info] [Error - 12:42:58 AM] (18408) File or directory "\<default workspace root>" does not exist.
2025-03-18 00:42:58.424 [info] [Info  - 12:42:58 AM] (18408) No source files found.
2025-03-18 00:42:58.827 [info] [Info  - 12:42:58 AM] (18408) Background analysis(3) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-18 00:42:58.827 [info] [Info  - 12:42:58 AM] (18408) Background analysis(3) started
